steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Prisma generate untuk membuat client
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'prisma', 'generate']

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/diy-api:latest'
      - '.'

  # Step 4: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/diy-api:latest'

  # Step 5: Deploy to Cloud Run (development)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'diy-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/diy-api:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=projects/$PROJECT_ID/secrets/database_url:latest'

timeout: 1200s
