steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/diy-api/diy-api-development:$COMMIT_SHA',
        '.',
      ]

  # Step 2: Push Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/diy-api/diy-api-development:$COMMIT_SHA',
      ]

  # Step 3: Deploy to Cloud Run for Development
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'diy-api-development'  # Nama service Cloud Run untuk development
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/diy-api/diy-api-development:$COMMIT_SHA'
      - '--allow-unauthenticated'  # Mengizinkan akses tanpa otentikasi
      - --service-account
      - 'cloud-run-diy-capstone-dev@diy-capstone-dev.iam.gserviceaccount.com'  # Ganti dengan service account untuk dev
      - '--region'
      - 'asia-southeast2'  # Ganti dengan region yang sesuai
      - '--cpu'
      - '0.5'  # Alokasi CPU lebih rendah dibandingkan dengan production
      - '--memory'
      - '512Mi'  # Alokasi memori lebih rendah
      - '--min-instances'
      - '0'  # Biarkan 0 untuk menghemat biaya selama idle
      - '--max-instances'
      - '2'  # Maksimal dua instances untuk development

    secretEnv: ['DATABASE_URL', 'FIREBASE_SERVICE_ACCOUNT']  # Mendeklarasikan variabel lingkungan untuk secrets

options:
  logging: CLOUD_LOGGING_ONLY  # Menggunakan Cloud Logging

images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/diy-api/diy-api-development:$COMMIT_SHA'  # Image yang akan digunakan

availableSecrets:
  secretManager:
    # Menyimpan secret di Google Cloud Secret Manager dan menjadikannya variabel lingkungan
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: 'DATABASE_URL'  # Menetapkan SECRET untuk DATABASE_URL
    - versionName: projects/$PROJECT_ID/secrets/firebase-service-account/versions/latest
      env: 'FIREBASE_SERVICE_ACCOUNT'  # Menetapkan secret untuk Firebase Service Account JSON